total_bill = float(input("Total bill amount? "))
service = input("Level of service? ").lower()
split = float(input("Split how many ways? "))
good = float(0.20 * total_bill)
fair = float(0.15 * total_bill)
bad = float(0.10 * total_bill)
good_bill = float(good + total_bill)
fair_bill = float(fair + total_bill)
bad_bill = float(bad + total_bill)
good_split = float((good + total_bill) / split)
fair_split = float((fair + total_bill) / split)
bad_split = float((bad + total_bill) / split)
if service == "good":
    print("Tip amount: {:0.2f}".format(good))
    print("Total amount: {:0.2f}".format(good_bill))
    print("Amount per person: {:0.2f}".format(good_split))
if service == "fair":
    print("Tip amount: {:0.2f}".format(fair))
    print("Total amount: {:0.2f}".format(fair_bill))
    print("Amount per person: {:0.2f}".format(fair_split))
if service == "bad":
    print("Tip amount: {:0.2f}".format(bad))
    print("Total amount: {:0.2f}".format(bad_bill))
    print("Amount per person: {:0.2f}".format(bad_split))
